<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>LinuxWebTool.WebHost</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <!-- 发布时将前端资源嵌入主程序；开发环境仍保留物理 wwwroot 便于调试。 -->
    <EmbeddedResource Include="wwwroot\**" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinuxWebTool.Infrastructure\LinuxWebTool.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- 杩愯鏈熸暟鎹洰褰曪紙鏁版嵁搴?鍑嵁/瀵嗛挜/鏃ュ織锛夌粷涓嶈兘杩涘彂甯冧骇鐗╋細鍑嵁浼氶殢鍖呮硠婕?-->
    <None Remove="data\**" />
    <Content Remove="data\**" />
    <None Update="wwwroot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>


  <ItemGroup>
    <TrimmerRootAssembly Include="Quartz" />
  </ItemGroup>
</Project>

