<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- 持久化 -->
    <PackageVersion Include="Dapper" Version="2.1.35" />
    <PackageVersion Include="Dapper.AOT" Version="1.0.52" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <!-- 定时调度 -->
    <PackageVersion Include="Quartz.Extensions.Hosting" Version="3.18.2" />
    <!-- 认证 -->
    <PackageVersion Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.4.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <!-- API 文档（AOT 兼容）-->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.6.0" />
    <!-- Microsoft.Extensions -->
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.2" />
    <!-- 测试 -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.1" />
  </ItemGroup>
</Project>