import os
def r(path, old, new):
    with open(path, 'r', encoding='utf-8') as f: c = f.read()
    c = c.replace(old, new)
    with open(path, 'w', encoding='utf-8') as f: f.write(c)

path = "src/LinuxWebTool.WebHost/Routes/FilesController.cs"
r(path, 'new { message = "程序数据目录禁止写入" }', 'new MessageResponse("程序数据目录禁止写入")')
r(path, 'new { message = "目标目录不存在，请先创建目录" }', 'new MessageResponse("目标目录不存在，请先创建目录")')
r(path, 'new { message = "内容超过大小限制" }', 'new MessageResponse("内容超过大小限制")')
r(path, 'new { message = "已保存" }', 'new MessageResponse("已保存")')
r(path, 'new { message = "同名文件或目录已存在" }', 'new MessageResponse("同名文件或目录已存在")')
r(path, 'new { message = $"创建目录失败：{ex.Message}" }', 'new MessageResponse($"创建目录失败：{ex.Message}")')
r(path, 'new { message = "不能对根目录进行操作" }', 'new MessageResponse("不能对根目录进行操作")')
r(path, 'new { message = "程序数据目录禁止重命名 / 移动" }', 'new MessageResponse("程序数据目录禁止重命名 / 移动")')
r(path, 'new\r\n { message = "目标已存在同名文件" }', 'new MessageResponse("目标已存在同名文件")')
r(path, 'new\r\n { message = "目标已存在同名目录" }', 'new MessageResponse("目标已存在同名目录")')
r(path, 'new { message = "目标已存在同名文件" }', 'new MessageResponse("目标已存在同名文件")')
r(path, 'new { message = "目标已存在同名目录" }', 'new MessageResponse("目标已存在同名目录")')
r(path, 'new { message = "源路径不存在" }', 'new MessageResponse("源路径不存在")')
r(path, 'new { message = "不能删除根目录" }', 'new MessageResponse("不能删除根目录")')
r(path, 'new { message = "程序数据目录禁止删除" }', 'new MessageResponse("程序数据目录禁止删除")')
r(path, 'new { message = "路径不存在" }', 'new MessageResponse("路径不存在")')
r(path, 'new { message = "已删除" }', 'new MessageResponse("已删除")')
r(path, 'new { message = $"目录不存在：{normalized}" }', 'new MessageResponse($"目录不存在：{normalized}")')
r(path, 'new { message = "未选择文件" }', 'new MessageResponse("未选择文件")')
r(path, 'new { message = "文件名无效" }', 'new MessageResponse("文件名无效")')
r(path, 'new { message = $"读取目录失败：{ex.Message}" }', 'new MessageResponse($"读取目录失败：{ex.Message}")')
r(path, 'new { message = $"无权限读取该目录：{normalized}" }', 'new MessageResponse($"无权限读取该目录：{normalized}")')
r(path, 'new { message = $"路径不存在或不是目录：{normalized}" }', 'new MessageResponse($"路径不存在或不是目录：{normalized}")')
r(path, 'new { message = $"文件不存在：{normalized}" }', 'new MessageResponse($"文件不存在：{normalized}")')
