using System.Text.Json.Serialization;
using LinuxWebTool.WebHost.Routes;
using LinuxWebTool.Infrastructure.Persistence.Entities;
using LinuxWebTool.Contracts.Models;
using LinuxWebTool.Infrastructure.Persistence;

namespace LinuxWebTool.WebHost.Composition;

[JsonSerializable(typeof(ChangeCredentialResponse))]
[JsonSerializable(typeof(CommandGroup))]
[JsonSerializable(typeof(CommandItemResponse))]
[JsonSerializable(typeof(CreateFileResponse))]
[JsonSerializable(typeof(DeleteFileErrorResponse))]
[JsonSerializable(typeof(ExecutionRecord))]
[JsonSerializable(typeof(FileContentResponse))]
[JsonSerializable(typeof(GroupItemResponse))]
[JsonSerializable(typeof(IdResponse))]
[JsonSerializable(typeof(ImportResponse))]
[JsonSerializable(typeof(LinuxCommand))]
[JsonSerializable(typeof(LogContentResponse))]
[JsonSerializable(typeof(MessageResponse))]
[JsonSerializable(typeof(EnqueueResponse))]
[JsonSerializable(typeof(OperationLog))]
[JsonSerializable(typeof(ReadFileErrorResponse))]
[JsonSerializable(typeof(RenameFileResponse))]
[JsonSerializable(typeof(RuleStatusResponse))]
[JsonSerializable(typeof(ScheduleStatusResponse))]
[JsonSerializable(typeof(ScheduleTask))]
[JsonSerializable(typeof(SmbMount))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.CommandGroup>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.ExecutionRecord>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.LinuxCommand>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.OperationLog>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.ScheduleTask>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.SmbMount>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.SystemStatusDiskSnapshot>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.SystemStatusNetSnapshot>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.SystemStatusProcessSnapshot>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.SystemStatusSnapshot>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.TranscodeJob>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.TranscodePreset>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Persistence.Entities.WatchRule>))]
[JsonSerializable(typeof(System.Collections.Generic.List<string>))]
[JsonSerializable(typeof(SystemStatusDiskSnapshot))]
[JsonSerializable(typeof(SystemStatusNetSnapshot))]
[JsonSerializable(typeof(SystemStatusProcessSnapshot))]
[JsonSerializable(typeof(SystemStatusSnapshot))]
[JsonSerializable(typeof(TranscodeJob))]
[JsonSerializable(typeof(TranscodePreset))]
[JsonSerializable(typeof(UploadFileResponse))]
[JsonSerializable(typeof(UserInfoResponse))]
[JsonSerializable(typeof(WatchRule))]
[JsonSerializable(typeof(CommandItemResponse))]
[JsonSerializable(typeof(SmbMountItemResponse))]
[JsonSerializable(typeof(SmbSupportResponse))]
[JsonSerializable(typeof(ResourceHistoryResponse))]
[JsonSerializable(typeof(List<CommandItemResponse>))]
[JsonSerializable(typeof(List<SmbMountItemResponse>))]
[JsonSerializable(typeof(IEnumerable<PresetItemResponse>))]
[JsonSerializable(typeof(IEnumerable<WatchRuleItemResponse>))]
[JsonSerializable(typeof(FileListResponse))]
[JsonSerializable(typeof(FileEntryResponse))]
[JsonSerializable(typeof(IEnumerable<ScheduleItemResponse>))]
[JsonSerializable(typeof(List<LogFileItemResponse>))]
[JsonSerializable(typeof(PagedResult<OperationLog>))]
[JsonSerializable(typeof(PagedResult<ExecutionRecord>))]

[JsonSerializable(typeof(PagedResponse<LinuxCommand>))]
[JsonSerializable(typeof(PagedResponse<OperationLog>))]
[JsonSerializable(typeof(PagedResponse<TranscodeJobBrief>))]
[JsonSerializable(typeof(PresetImportItem))]
[JsonSerializable(typeof(IEnumerable<PresetImportItem>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(List<LinuxWebTool.WebHost.Routes.GroupBrief>))]
[JsonSerializable(typeof(ChangeCredentialRequest))]
[JsonSerializable(typeof(CpuStatus))]
[JsonSerializable(typeof(DiskSnapshotPoint))]
[JsonSerializable(typeof(DiskStatus))]
[JsonSerializable(typeof(ExecuteCommandRequest))]
[JsonSerializable(typeof(ExecuteHistoryQuery))]
[JsonSerializable(typeof(ExecuteResult))]
[JsonSerializable(typeof(ExecutionRecordBrief))]
[JsonSerializable(typeof(FfmpegDetection))]
[JsonSerializable(typeof(GroupBrief))]
[JsonSerializable(typeof(HardwareDevice))]
[JsonSerializable(typeof(HostInfo))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResult))]
[JsonSerializable(typeof(MemoryStatus))]
[JsonSerializable(typeof(NetSnapshotPoint))]
[JsonSerializable(typeof(NetworkStatus))]
[JsonSerializable(typeof(OperationLogQuery))]
[JsonSerializable(typeof(OverviewResult))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Routes.FilesController.PathRequest))]
[JsonSerializable(typeof(ProcessSnapshotPoint))]
[JsonSerializable(typeof(ProcessStatus))]
[JsonSerializable(typeof(QuickExecuteRequest))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Routes.FilesController.RenameRequest))]
[JsonSerializable(typeof(SaveCommandRequest))]
[JsonSerializable(typeof(SaveGroupRequest))]
[JsonSerializable(typeof(SavePresetRequest))]
[JsonSerializable(typeof(SaveScheduleRequest))]
[JsonSerializable(typeof(SaveSmbMountRequest))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Routes.FilesController.SaveTextRequest))]
[JsonSerializable(typeof(SaveWatchRuleRequest))]
[JsonSerializable(typeof(ScheduleBrief))]
[JsonSerializable(typeof(ShellRequest))]
[JsonSerializable(typeof(ShellResult))]
[JsonSerializable(typeof(StatusSnapshotPoint))]
[JsonSerializable(typeof(SystemStatusResult))]
[JsonSerializable(typeof(TranscodeJobBrief))]
[JsonSerializable(typeof(TranscodeSubmitRequest))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Routes.SmbMountsController.UnmountRequest))]
[JsonSerializable(typeof(System.Collections.Generic.List<LinuxWebTool.Contracts.Models.PresetImportItem>))]
public partial class AppJsonSerializerContext
 : JsonSerializerContext
{
}




