using System.Text.Json.Serialization;
using LinuxWebTool.Infrastructure.Shared.Persistence.Entities;
using LinuxWebTool.Infrastructure.Shared.Persistence;

namespace LinuxWebTool.WebHost.Composition;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, PropertyNameCaseInsensitive = true)]
[JsonSerializable(typeof(ChangeCredentialResponse))]
[JsonSerializable(typeof(CommandGroup))]
[JsonSerializable(typeof(CommandItemResponse))]
[JsonSerializable(typeof(CreateFileResponse))]
[JsonSerializable(typeof(DeleteFileErrorResponse))]
[JsonSerializable(typeof(ExecutionRecord))]
[JsonSerializable(typeof(FileContentResponse))]
[JsonSerializable(typeof(GroupItemResponse))]
[JsonSerializable(typeof(IdResponse))]
[JsonSerializable(typeof(ImportResponse))]
[JsonSerializable(typeof(LinuxCommand))]
[JsonSerializable(typeof(LogContentResponse))]
[JsonSerializable(typeof(MessageResponse))]
[JsonSerializable(typeof(EnqueueResponse))]
[JsonSerializable(typeof(OperationLog))]
[JsonSerializable(typeof(ReadFileErrorResponse))]
[JsonSerializable(typeof(RenameFileResponse))]
[JsonSerializable(typeof(RuleStatusResponse))]
[JsonSerializable(typeof(ScheduleStatusResponse))]
[JsonSerializable(typeof(ScheduleTask))]
[JsonSerializable(typeof(SmbMount))]
[JsonSerializable(typeof(WebDavMount))]
[JsonSerializable(typeof(RcloneMount))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.CommandGroup>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.ExecutionRecord>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.LinuxCommand>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.OperationLog>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.ScheduleTask>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.SmbMount>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.SystemStatusDiskSnapshot>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.SystemStatusNetSnapshot>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.SystemStatusProcessSnapshot>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.SystemStatusSnapshot>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.TranscodeJob>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.TranscodePreset>))]
[JsonSerializable(typeof(System.Collections.Generic.IEnumerable<LinuxWebTool.Infrastructure.Shared.Persistence.Entities.WatchRule>))]
[JsonSerializable(typeof(System.Collections.Generic.List<string>))]
[JsonSerializable(typeof(SystemStatusDiskSnapshot))]
[JsonSerializable(typeof(SystemStatusNetSnapshot))]
[JsonSerializable(typeof(SystemStatusProcessSnapshot))]
[JsonSerializable(typeof(SystemStatusSnapshot))]
[JsonSerializable(typeof(TranscodeJob))]
[JsonSerializable(typeof(TranscodePreset))]
[JsonSerializable(typeof(UploadFileResponse))]
[JsonSerializable(typeof(UserInfoResponse))]
[JsonSerializable(typeof(WatchRule))]
[JsonSerializable(typeof(CommandItemResponse))]
[JsonSerializable(typeof(SmbMountItemResponse))]
[JsonSerializable(typeof(MountTaskInfo))]
[JsonSerializable(typeof(WebDavMountItemResponse))]
[JsonSerializable(typeof(RcloneMountItemResponse))]
[JsonSerializable(typeof(SmbSupportResponse))]
[JsonSerializable(typeof(ResourceHistoryResponse))]
[JsonSerializable(typeof(List<CommandItemResponse>))]
[JsonSerializable(typeof(List<SmbMountItemResponse>))]
[JsonSerializable(typeof(List<WebDavMountItemResponse>))]
[JsonSerializable(typeof(List<RcloneMountItemResponse>))]
[JsonSerializable(typeof(IEnumerable<PresetItemResponse>))]
[JsonSerializable(typeof(IEnumerable<WatchRuleItemResponse>))]
[JsonSerializable(typeof(FileListResponse))]
[JsonSerializable(typeof(FileEntryResponse))]
[JsonSerializable(typeof(IEnumerable<ScheduleItemResponse>))]
[JsonSerializable(typeof(List<LogFileItemResponse>))]
[JsonSerializable(typeof(PagedResult<OperationLog>))]
[JsonSerializable(typeof(PagedResult<ExecutionRecord>))]

[JsonSerializable(typeof(PagedResponse<LinuxCommand>))]
[JsonSerializable(typeof(PagedResponse<OperationLog>))]
[JsonSerializable(typeof(PagedResponse<TranscodeJobBrief>))]
[JsonSerializable(typeof(PresetImportItem))]
[JsonSerializable(typeof(IEnumerable<PresetImportItem>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(List<GroupBrief>))]
[JsonSerializable(typeof(ChangeCredentialRequest))]
[JsonSerializable(typeof(CpuStatus))]
[JsonSerializable(typeof(DiskSnapshotPoint))]
[JsonSerializable(typeof(DiskStatus))]
[JsonSerializable(typeof(ExecuteCommandRequest))]
[JsonSerializable(typeof(ExecuteHistoryQuery))]
[JsonSerializable(typeof(ExecuteResult))]
[JsonSerializable(typeof(ExecutionRecordBrief))]
[JsonSerializable(typeof(FfmpegDetection))]
[JsonSerializable(typeof(GroupBrief))]
[JsonSerializable(typeof(HardwareDevice))]
[JsonSerializable(typeof(HostInfo))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResult))]
[JsonSerializable(typeof(MemoryStatus))]
[JsonSerializable(typeof(NetSnapshotPoint))]
[JsonSerializable(typeof(NetworkStatus))]
[JsonSerializable(typeof(OperationLogQuery))]
[JsonSerializable(typeof(MountHealthSnapshot))]
[JsonSerializable(typeof(OverviewResult))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Features.Files.Routes.FilesController.PathRequest))]
[JsonSerializable(typeof(ProcessSnapshotPoint))]
[JsonSerializable(typeof(ProcessStatus))]
[JsonSerializable(typeof(QuickExecuteRequest))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Features.Files.Routes.FilesController.RenameRequest))]
[JsonSerializable(typeof(SaveCommandRequest))]
[JsonSerializable(typeof(SaveGroupRequest))]
[JsonSerializable(typeof(SavePresetRequest))]
[JsonSerializable(typeof(SaveScheduleRequest))]
[JsonSerializable(typeof(SaveSmbMountRequest))]
[JsonSerializable(typeof(SaveWebDavMountRequest))]
[JsonSerializable(typeof(SaveRcloneMountRequest))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Features.Files.Routes.FilesController.SaveTextRequest))]
[JsonSerializable(typeof(SaveWatchRuleRequest))]
[JsonSerializable(typeof(ScheduleBrief))]
[JsonSerializable(typeof(ShellRequest))]
[JsonSerializable(typeof(ShellResult))]
[JsonSerializable(typeof(StatusSnapshotPoint))]
[JsonSerializable(typeof(SystemStatusResult))]
[JsonSerializable(typeof(TranscodeJobBrief))]
[JsonSerializable(typeof(TranscodeSubmitRequest))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Features.Mount.Routes.SmbMountsController.UnmountRequest))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Features.Mount.Routes.WebDavMountsController.WebDavUnmountRequest))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Shared.Routes.HealthResponse))]
[JsonSerializable(typeof(System.Collections.Generic.List<LinuxWebTool.Contracts.Features.Transcode.Contracts.PresetImportItem>))]
[JsonSerializable(typeof(LinuxWebTool.Contracts.Features.Terminal.Contracts.TerminalSessionCreateRequest))]
[JsonSerializable(typeof(LinuxWebTool.Contracts.Features.Terminal.Contracts.TerminalSessionCreateResponse))]
[JsonSerializable(typeof(LinuxWebTool.Contracts.Features.Terminal.Contracts.TerminalSessionInfo))]
[JsonSerializable(typeof(LinuxWebTool.Contracts.Features.Terminal.Contracts.TerminalSessionInfo[]))]
[JsonSerializable(typeof(LinuxWebTool.Contracts.Features.Terminal.Contracts.TerminalSessionUpdateRequest))]
[JsonSerializable(typeof(LinuxWebTool.Contracts.Features.Terminal.Contracts.TerminalAttachmentTicket))]
[JsonSerializable(typeof(LinuxWebTool.Contracts.Features.Terminal.Contracts.TerminalOutputFrame))]
[JsonSerializable(typeof(LinuxWebTool.Infrastructure.Features.Terminal.Platform.TerminalCapabilities))]

// API Key Models
[JsonSerializable(typeof(CreateApiKeyRequest))]
[JsonSerializable(typeof(UpdateApiKeyRequest))]
[JsonSerializable(typeof(ApiKeyItemResponse))]
[JsonSerializable(typeof(ApiKeyCreatedResponse))]
[JsonSerializable(typeof(List<ApiKeyItemResponse>))]
[JsonSerializable(typeof(ApiKeyEntity))]
[JsonSerializable(typeof(List<ApiKeyEntity>))]

// FRP Tunnel Models
[JsonSerializable(typeof(UpdateFrpConfigRequest))]
[JsonSerializable(typeof(FrpTunnelConfigDto))]
[JsonSerializable(typeof(FrpTunnelStatusDto))]
[JsonSerializable(typeof(FrpTunnelLogItem))]
[JsonSerializable(typeof(List<FrpTunnelLogItem>))]
[JsonSerializable(typeof(FrpTunnelConfigEntity))]
[JsonSerializable(typeof(FrpTunnelLineDto))]
[JsonSerializable(typeof(List<FrpTunnelLineDto>))]
[JsonSerializable(typeof(CreateFrpTunnelLineRequest))]
[JsonSerializable(typeof(UpdateFrpTunnelLineRequest))]
[JsonSerializable(typeof(FrpTunnelLineEntity))]
[JsonSerializable(typeof(List<FrpTunnelLineEntity>))]

// Gateway Models
[JsonSerializable(typeof(GatewayRouteItem))]
[JsonSerializable(typeof(List<GatewayRouteItem>))]
[JsonSerializable(typeof(SaveGatewayRouteRequest))]
[JsonSerializable(typeof(GatewayClusterItem))]
[JsonSerializable(typeof(List<GatewayClusterItem>))]
[JsonSerializable(typeof(SaveGatewayClusterRequest))]
[JsonSerializable(typeof(GatewayWebsiteItem))]
[JsonSerializable(typeof(List<GatewayWebsiteItem>))]
[JsonSerializable(typeof(SaveGatewayWebsiteRequest))]
[JsonSerializable(typeof(GatewayTcpRouteItem))]
[JsonSerializable(typeof(List<GatewayTcpRouteItem>))]
[JsonSerializable(typeof(SaveGatewayTcpRouteRequest))]
[JsonSerializable(typeof(GatewayRouteEntity))]
[JsonSerializable(typeof(List<GatewayRouteEntity>))]
[JsonSerializable(typeof(GatewayClusterEntity))]
[JsonSerializable(typeof(List<GatewayClusterEntity>))]
[JsonSerializable(typeof(GatewayWebsiteEntity))]
[JsonSerializable(typeof(List<GatewayWebsiteEntity>))]
[JsonSerializable(typeof(GatewayTcpRouteEntity))]
[JsonSerializable(typeof(List<GatewayTcpRouteEntity>))]
[JsonSerializable(typeof(LinuxWebTool.WebHost.Features.Gateway.Adapters.DatabaseProxyConfigProvider.DestinationItem))]
[JsonSerializable(typeof(List<LinuxWebTool.WebHost.Features.Gateway.Adapters.DatabaseProxyConfigProvider.DestinationItem>))]

// MCP Models
[JsonSerializable(typeof(McpRpcRequest))]
[JsonSerializable(typeof(McpRpcResponse))]
[JsonSerializable(typeof(McpRpcError))]
[JsonSerializable(typeof(McpToolDefinition))]
[JsonSerializable(typeof(McpToolContent))]
[JsonSerializable(typeof(McpCallToolResult))]
[JsonSerializable(typeof(McpToolsListResult))]
[JsonSerializable(typeof(List<McpToolDefinition>))]
[JsonSerializable(typeof(List<McpToolContent>))]

// EasyTier Models
[JsonSerializable(typeof(EasyTierNodeConfigDto))]
[JsonSerializable(typeof(List<EasyTierNodeConfigDto>))]
[JsonSerializable(typeof(CreateEasyTierNodeRequest))]
[JsonSerializable(typeof(UpdateEasyTierNodeRequest))]
[JsonSerializable(typeof(EasyTierNodeStatusDto))]
[JsonSerializable(typeof(List<EasyTierNodeStatusDto>))]
[JsonSerializable(typeof(EasyTierNodeDetailDto))]
[JsonSerializable(typeof(EasyTierPeerDetailDto))]
[JsonSerializable(typeof(List<EasyTierPeerDetailDto>))]
[JsonSerializable(typeof(EasyTierRouteDetailDto))]
[JsonSerializable(typeof(List<EasyTierRouteDetailDto>))]
[JsonSerializable(typeof(EasyTierPatchRequestDto))]
[JsonSerializable(typeof(EasyTierPatchResultDto))]
[JsonSerializable(typeof(EasyTierEngineStatusDto))]
[JsonSerializable(typeof(EasyTierUpgradeResultDto))]
[JsonSerializable(typeof(EasyTierGitHubReleaseInfoDto))]
[JsonSerializable(typeof(InstallGitHubReleaseRequest))]
[JsonSerializable(typeof(EasyTierAvailablePortDto))]
[JsonSerializable(typeof(List<int>))]
[JsonSerializable(typeof(EasyTierNodeEntity))]
[JsonSerializable(typeof(List<EasyTierNodeEntity>))]

public partial class AppJsonSerializerContext
 : JsonSerializerContext
{
}
