import os
import re

routes_dir = "src/LinuxWebTool.WebHost/Routes"
output_file = "src/LinuxWebTool.WebHost/MinimalApi/EndpointsMapper.g.cs"

out_lines = [
    "// <auto-generated />",
    "using Microsoft.AspNetCore.Builder;",
    "using Microsoft.AspNetCore.Http;",
    "using Microsoft.AspNetCore.Mvc;",
    "using Microsoft.Extensions.DependencyInjection;",
    "using LinuxWebTool.WebHost.Routes;",
    "using LinuxWebTool.Contracts.Models;",
    "using System;",
    "using System.Threading.Tasks;",
    "",
]

map_lines = [
    "        public static void MapAutoControllers(this WebApplication app)",
    "        {",
]

class_names = []
for filename in os.listdir(routes_dir):
    if not filename.endswith("Controller.cs"): continue
    class_name = filename.replace(".cs", "")
    class_names.append(class_name)
    out_lines.append(f"using static LinuxWebTool.WebHost.Routes.{class_name};")
    
out_lines.extend([
    "",
    "namespace LinuxWebTool.WebHost.MinimalApi",
    "{",
    "    public static class EndpointsMapper",
    "    {",
    "        public static void AddAutoControllers(this IServiceCollection services)",
    "        {",
])

for class_name in class_names:
    out_lines.append(f"            services.AddScoped<{class_name}>();")
    
    filepath = os.path.join(routes_dir, class_name + ".cs")
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
        
    class_match = re.search(r'public\s+class\s+(' + class_name + r')', content)
    if not class_match:
        continue
    
    route_prefix = ""
    route_match = re.search(r'\[Route\("([^"]+)"\)\]', content)
    if route_match:
        route_prefix = route_match.group(1).replace("[controller]", class_name.replace("Controller", ""))
    if not route_prefix.startswith("/"):
        route_prefix = "/" + route_prefix
        
    group_var = "group_" + class_name
    map_lines.append(f"            var {group_var} = app.MapGroup(\"{route_prefix}\");")
    
    before_class = content.split(class_match.group(0))[0]
    if "[Authorize]" in before_class:
        map_lines.append(f"            {group_var}.RequireAuthorization();")
        
    lines = content.split('\n')
    current_verb = ""
    current_sub_route = ""
    current_has_allow_anon = False
    
    for i, line in enumerate(lines):
        verb_match = re.search(r'\[Http(Get|Post|Put|Delete|Patch)(?:\("([^"]*)"\))?\]', line)
        if verb_match:
            current_verb = verb_match.group(1)
            current_sub_route = verb_match.group(2) or ""
            
        if "[AllowAnonymous]" in line:
            current_has_allow_anon = True
            
        sig_match = re.search(r'public\s+(async\s+)?Task<IResult>\s+(\w+)\s*\((.*?)\)', line)
        if not sig_match and current_verb:
            if 'Task<IResult>' in line:
                combined = line
                for j in range(1, 5):
                    if i + j < len(lines):
                        combined += " " + lines[i+j].strip()
                        if ')' in combined:
                            break
                sig_match = re.search(r'public\s+(async\s+)?Task<IResult>\s+(\w+)\s*\((.*?)\)', combined)

        if sig_match and current_verb:
            is_async = sig_match.group(1) is not None
            method_name = sig_match.group(2)
            params_str = sig_match.group(3).strip()
            
            params_list = []
            call_args = []
            if params_str:
                raw_params = re.split(r',\s*(?![^<]*>)', params_str)
                for rp in raw_params:
                    rp = rp.strip()
                    if not rp: continue
                    params_list.append(rp)
                    name_part = rp.split('=')[0].strip()
                    parts = name_part.split(' ')
                    param_name = parts[-1]
                    call_args.append(param_name)
                    
            lambda_params = f"[FromServices] {class_name} ctrl, HttpContext ctx"
            if params_list:
                lambda_params += ", " + ", ".join(params_list).replace("[FromQuery] OperationLogQuery", "[AsParameters] OperationLogQuery").replace("[FromQuery] ExecuteHistoryQuery", "[AsParameters] ExecuteHistoryQuery")
                
            call_params = ", ".join(call_args)
            
            if is_async:
                lambda_body = f"{{ ctrl.HttpContext = ctx; return await ctrl.{method_name}({call_params}); }}"
            else:
                lambda_body = f"{{ ctrl.HttpContext = ctx; return ctrl.{method_name}({call_params}); }}"
                
            map_stmt = f"            {group_var}.Map{current_verb}(\"{current_sub_route}\", async ({lambda_params}) => {lambda_body})"
            if current_has_allow_anon:
                map_stmt += ".AllowAnonymous()"
            map_stmt += ";"
            map_lines.append(map_stmt)
            
            current_verb = ""
            current_sub_route = ""
            current_has_allow_anon = False

out_lines.append("        }")
out_lines.append("")
out_lines.extend(map_lines)
out_lines.append("        }")
out_lines.append("    }")
out_lines.append("}")

with open(output_file, "w", encoding="utf-8") as f:
    f.write("\n".join(out_lines))
    
print("Generated EndpointsMapper.g.cs")

