#nullable enable
// <auto-generated />
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using LinuxWebTool.WebHost.Routes;
using LinuxWebTool.Contracts.Models;
using System;
using System.Threading.Tasks;

using static LinuxWebTool.WebHost.Routes.AuthController;
using static LinuxWebTool.WebHost.Routes.CommandsController;
using static LinuxWebTool.WebHost.Routes.FilesController;
using static LinuxWebTool.WebHost.Routes.GroupsController;
using static LinuxWebTool.WebHost.Routes.HistoryController;
using static LinuxWebTool.WebHost.Routes.LogsController;
using static LinuxWebTool.WebHost.Routes.OverviewController;
using static LinuxWebTool.WebHost.Routes.SchedulesController;
using static LinuxWebTool.WebHost.Routes.SmbMountsController;
using static LinuxWebTool.WebHost.Routes.SystemStatusController;
using static LinuxWebTool.WebHost.Routes.TranscodeController;

namespace LinuxWebTool.WebHost.MinimalApi
{
    public static class EndpointsMapper
    {
        public static void AddAutoControllers(this IServiceCollection services)
        {
            services.AddScoped<AuthController>();
            services.AddScoped<CommandsController>();
            services.AddScoped<FilesController>();
            services.AddScoped<GroupsController>();
            services.AddScoped<HistoryController>();
            services.AddScoped<LogsController>();
            services.AddScoped<OverviewController>();
            services.AddScoped<SchedulesController>();
            services.AddScoped<SmbMountsController>();
            services.AddScoped<SystemStatusController>();
            services.AddScoped<TranscodeController>();
        }

        public static void MapAutoControllers(this WebApplication app)
        {
            var group_AuthController = app.MapGroup("/api/Auth");
            group_AuthController.MapPost("Login", async ([FromServices] AuthController ctrl, HttpContext ctx, [FromBody] LoginRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Login(request); }).AllowAnonymous();
            group_AuthController.MapGet("Check", ([FromServices] AuthController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.Check(); });
            group_AuthController.MapPost("ChangeCredential", async ([FromServices] AuthController ctrl, HttpContext ctx, [FromBody] ChangeCredentialRequest request) => { ctrl.HttpContext = ctx; return await ctrl.ChangeCredential(request); });
            var group_CommandsController = app.MapGroup("/api/Commands");
            group_CommandsController.RequireAuthorization();
            group_CommandsController.MapGet("", async ([FromServices] CommandsController ctrl, HttpContext ctx, [FromQuery] Guid? groupId, [FromQuery] string? keyword) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(groupId, keyword); });
            group_CommandsController.MapPost("", async ([FromServices] CommandsController ctrl, HttpContext ctx, [FromBody] SaveCommandRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_CommandsController.MapPut("{id:guid}", async ([FromServices] CommandsController ctrl, HttpContext ctx, Guid id, [FromBody] SaveCommandRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_CommandsController.MapDelete("{id:guid}", async ([FromServices] CommandsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            group_CommandsController.MapPost("{id:guid}/Execute", async ([FromServices] CommandsController ctrl, HttpContext ctx, Guid id, [FromBody] ExecuteCommandRequest? request) => { ctrl.HttpContext = ctx; return await ctrl.Execute(id, request); });
            group_CommandsController.MapPost("QuickExecute", async ([FromServices] CommandsController ctrl, HttpContext ctx, [FromBody] QuickExecuteRequest request) => { ctrl.HttpContext = ctx; return await ctrl.QuickExecute(request); });
            group_CommandsController.MapGet("{id:guid}/History", async ([FromServices] CommandsController ctrl, HttpContext ctx, Guid id, [FromQuery] int page = 1, [FromQuery] int pageSize = 20) => { ctrl.HttpContext = ctx; return await ctrl.History(id, page, pageSize); });
            var group_FilesController = app.MapGroup("/api/Files");
            group_FilesController.RequireAuthorization();
            group_FilesController.MapGet("", ([FromServices] FilesController ctrl, HttpContext ctx, [FromQuery] string path) => { ctrl.HttpContext = ctx; return ctrl.List(path); });
            group_FilesController.MapGet("Content", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromQuery] string path) => { ctrl.HttpContext = ctx; return await ctrl.ReadContent(path); });
            group_FilesController.MapPost("Content", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromBody] SaveTextRequest request) => { ctrl.HttpContext = ctx; return await ctrl.WriteContent(request); });
            group_FilesController.MapPost("Mkdir", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromBody] PathRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Mkdir(request); });
            group_FilesController.MapPost("Rename", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromBody] RenameRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Rename(request); });
            group_FilesController.MapDelete("", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromQuery] string path, [FromQuery] bool recursive = false) => { ctrl.HttpContext = ctx; return await ctrl.Delete(path, recursive); });
            group_FilesController.MapPost("Upload", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromQuery] string path, IFormFile? file) => { ctrl.HttpContext = ctx; return await ctrl.Upload(path, file); });
            var group_GroupsController = app.MapGroup("/api/Groups");
            group_GroupsController.RequireAuthorization();
            group_GroupsController.MapGet("", async ([FromServices] GroupsController ctrl, HttpContext ctx, [FromQuery] GroupBizType bizType = GroupBizType.Command) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(bizType); });
            group_GroupsController.MapPost("", async ([FromServices] GroupsController ctrl, HttpContext ctx, [FromBody] SaveGroupRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_GroupsController.MapPut("{id:guid}", async ([FromServices] GroupsController ctrl, HttpContext ctx, Guid id, [FromBody] SaveGroupRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_GroupsController.MapDelete("{id:guid}", async ([FromServices] GroupsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            var group_HistoryController = app.MapGroup("/api/History");
            group_HistoryController.RequireAuthorization();
            group_HistoryController.MapGet("", async ([FromServices] HistoryController ctrl, HttpContext ctx, [AsParameters] ExecuteHistoryQuery query) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(query); });
            group_HistoryController.MapDelete("", async ([FromServices] HistoryController ctrl, HttpContext ctx, [FromQuery] int? olderThanDays) => { ctrl.HttpContext = ctx; return await ctrl.Clear(olderThanDays); });
            var group_LogsController = app.MapGroup("/api/Logs");
            group_LogsController.RequireAuthorization();
            group_LogsController.MapGet("Operations", async ([FromServices] LogsController ctrl, HttpContext ctx, [AsParameters] OperationLogQuery query) => { ctrl.HttpContext = ctx; return await ctrl.Operations(query); });
            group_LogsController.MapGet("Files", ([FromServices] LogsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.Files(); });
            group_LogsController.MapGet("Files/{name}", ([FromServices] LogsController ctrl, HttpContext ctx, string name, [FromQuery] int tail = 300) => { ctrl.HttpContext = ctx; return ctrl.FileContent(name, tail); });
            var group_OverviewController = app.MapGroup("/api/Overview");
            group_OverviewController.RequireAuthorization();
            group_OverviewController.MapGet("", async ([FromServices] OverviewController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.Get(); });
            var group_SchedulesController = app.MapGroup("/api/Schedules");
            group_SchedulesController.RequireAuthorization();
            group_SchedulesController.MapGet("", async ([FromServices] SchedulesController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(); });
            group_SchedulesController.MapPost("", async ([FromServices] SchedulesController ctrl, HttpContext ctx, [FromBody] SaveScheduleRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_SchedulesController.MapPut("{id:guid}", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id, [FromBody] SaveScheduleRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_SchedulesController.MapDelete("{id:guid}", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            group_SchedulesController.MapPost("{id:guid}/Toggle", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Toggle(id); });
            group_SchedulesController.MapPost("{id:guid}/RunNow", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.RunNow(id); });
            group_SchedulesController.MapGet("{id:guid}/Records", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id, [FromQuery] int page = 1, [FromQuery] int pageSize = 20) => { ctrl.HttpContext = ctx; return await ctrl.Records(id, page, pageSize); });
            var group_SmbMountsController = app.MapGroup("/api/SmbMounts");
            group_SmbMountsController.RequireAuthorization();
            group_SmbMountsController.MapGet("Support", ([FromServices] SmbMountsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.Support(); });
            group_SmbMountsController.MapGet("", async ([FromServices] SmbMountsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(); });
            group_SmbMountsController.MapPost("", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, [FromBody] SaveSmbMountRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_SmbMountsController.MapPut("{id:guid}", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, Guid id, [FromBody] SaveSmbMountRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_SmbMountsController.MapDelete("{id:guid}", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            group_SmbMountsController.MapPost("{id:guid}/Mount", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Mount(id); });
            group_SmbMountsController.MapPost("{id:guid}/Unmount", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, Guid id, [FromBody] UnmountRequest? request) => { ctrl.HttpContext = ctx; return await ctrl.Unmount(id, request); });
            var group_SystemStatusController = app.MapGroup("/api/SystemStatus");
            group_SystemStatusController.RequireAuthorization();
            group_SystemStatusController.MapGet("", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, CancellationToken cancellationToken) => { ctrl.HttpContext = ctx; return await ctrl.Get(cancellationToken); });
            group_SystemStatusController.MapGet("History", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.History(hours); });
            group_SystemStatusController.MapGet("DiskHistory", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.DiskHistory(hours); });
            group_SystemStatusController.MapGet("NetHistory", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.NetHistory(hours); });
            group_SystemStatusController.MapGet("ProcessHistory", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.ProcessHistory(hours); });
            group_SystemStatusController.MapGet("ResourceHistory", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.ResourceHistory(hours); });
            var group_TranscodeController = app.MapGroup("/api/Transcode");
            group_TranscodeController.RequireAuthorization();
            group_TranscodeController.MapGet("Jobs", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromQuery] int page = 1, [FromQuery] int pageSize = 20, [FromQuery] TranscodeJobStatus? status = null, [FromQuery] Guid? watchRuleId = null) => { ctrl.HttpContext = ctx; return await ctrl.Jobs(page, pageSize, status, watchRuleId); });
            group_TranscodeController.MapPost("Submit", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromBody] TranscodeSubmitRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Submit(request); });
            group_TranscodeController.MapPost("Jobs/{id:guid}/Cancel", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Cancel(id); });
            group_TranscodeController.MapPost("Jobs/Retry/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Retry(id); });
            group_TranscodeController.MapPost("Jobs/ClearFinished", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.ClearFinished(); });
            group_TranscodeController.MapGet("Presets", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.Presets(); });
            group_TranscodeController.MapPost("Presets", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromBody] SavePresetRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreatePreset(request); });
            group_TranscodeController.MapPut("Presets/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id, [FromBody] SavePresetRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdatePreset(id, request); });
            group_TranscodeController.MapDelete("Presets/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.DeletePreset(id); });
            group_TranscodeController.MapGet("Presets/Export", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.ExportPresets(); });
            group_TranscodeController.MapPost("Presets/Import", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromBody] List<PresetImportItem> items) => { ctrl.HttpContext = ctx; return await ctrl.ImportPresets(items); });
            group_TranscodeController.MapGet("WatchRules", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.WatchRules(); });
            group_TranscodeController.MapPost("WatchRules", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromBody] SaveWatchRuleRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreateWatchRule(request); });
            group_TranscodeController.MapPut("WatchRules/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id, [FromBody] SaveWatchRuleRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdateWatchRule(id, request); });
            group_TranscodeController.MapDelete("WatchRules/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.DeleteWatchRule(id); });
            group_TranscodeController.MapPost("WatchRules/{id:guid}/Toggle", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.ToggleWatchRule(id); });
            group_TranscodeController.MapGet("DetectFfmpeg", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.DetectFfmpeg(); });
        }
    }
}

