#nullable enable
// <auto-generated />
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using LinuxWebTool.WebHost.Routes;
using LinuxWebTool.Contracts.Models;
using System;
using System.Threading.Tasks;

using static LinuxWebTool.WebHost.Routes.AuthController;
using static LinuxWebTool.WebHost.Routes.CommandsController;
using static LinuxWebTool.WebHost.Routes.FilesController;
using static LinuxWebTool.WebHost.Routes.GroupsController;
using static LinuxWebTool.WebHost.Routes.HistoryController;
using static LinuxWebTool.WebHost.Routes.LogsController;
using static LinuxWebTool.WebHost.Routes.OverviewController;
using static LinuxWebTool.WebHost.Routes.SchedulesController;
using static LinuxWebTool.WebHost.Routes.SmbMountsController;
using static LinuxWebTool.WebHost.Routes.SystemStatusController;
using static LinuxWebTool.WebHost.Routes.TranscodeController;

namespace LinuxWebTool.WebHost.MinimalApi
{
    public static class EndpointsMapper
    {
        public static void AddAutoControllers(this IServiceCollection services)
        {
            services.AddScoped<AuthController>();
            services.AddScoped<CommandsController>();
            services.AddScoped<FilesController>();
            services.AddScoped<GroupsController>();
            services.AddScoped<HistoryController>();
            services.AddScoped<LogsController>();
            services.AddScoped<OverviewController>();
            services.AddScoped<SchedulesController>();
            services.AddScoped<SmbMountsController>();
            services.AddScoped<WebDavMountsController>();
            services.AddScoped<RcloneMountsController>();
            services.AddScoped<MountTasksController>();
            services.AddScoped<SystemStatusController>();
            services.AddScoped<TranscodeController>();
            services.AddScoped<TerminalController>();
            services.AddScoped<ApiKeysController>();
            services.AddScoped<FrpTunnelController>();
            services.AddScoped<GatewayController>();
        }

        public static void MapAutoControllers(this WebApplication app)
        {
            var group_AuthController = app.MapGroup("/api/Auth");
            group_AuthController.MapPost("Login", async ([FromServices] AuthController ctrl, HttpContext ctx, [FromBody] LoginRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Login(request); }).AllowAnonymous();
            group_AuthController.MapGet("Check", ([FromServices] AuthController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.Check(); });
            group_AuthController.MapPost("ChangeCredential", async ([FromServices] AuthController ctrl, HttpContext ctx, [FromBody] ChangeCredentialRequest request) => { ctrl.HttpContext = ctx; return await ctrl.ChangeCredential(request); });

            var group_CommandsController = app.MapGroup("/api/Commands");
            group_CommandsController.RequireAuthorization();
            group_CommandsController.MapGet("", async ([FromServices] CommandsController ctrl, HttpContext ctx, [FromQuery] Guid? groupId, [FromQuery] string? keyword) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(groupId, keyword); });
            group_CommandsController.MapPost("", async ([FromServices] CommandsController ctrl, HttpContext ctx, [FromBody] SaveCommandRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_CommandsController.MapPut("{id:guid}", async ([FromServices] CommandsController ctrl, HttpContext ctx, Guid id, [FromBody] SaveCommandRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_CommandsController.MapDelete("{id:guid}", async ([FromServices] CommandsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            group_CommandsController.MapPost("{id:guid}/Execute", async ([FromServices] CommandsController ctrl, HttpContext ctx, Guid id) =>
            {
                ctrl.HttpContext = ctx;
                ExecuteCommandRequest? request = null;
                if (ctx.Request.HasJsonContentType() && ctx.Request.ContentLength is not (null or 0))
                {
                    request = await ctx.Request.ReadFromJsonAsync<ExecuteCommandRequest>(LinuxWebTool.WebHost.Composition.AppJsonSerializerContext.Default.ExecuteCommandRequest);
                }
                return await ctrl.Execute(id, request);
            });
            group_CommandsController.MapPost("QuickExecute", async ([FromServices] CommandsController ctrl, HttpContext ctx, [FromBody] QuickExecuteRequest request) => { ctrl.HttpContext = ctx; return await ctrl.QuickExecute(request); });
            group_CommandsController.MapGet("{id:guid}/History", async ([FromServices] CommandsController ctrl, HttpContext ctx, Guid id, [FromQuery] int page = 1, [FromQuery] int pageSize = 20) => { ctrl.HttpContext = ctx; return await ctrl.History(id, page, pageSize); });

            var group_FilesController = app.MapGroup("/api/Files");
            group_FilesController.RequireAuthorization();
            group_FilesController.MapGet("", ([FromServices] FilesController ctrl, HttpContext ctx, [FromQuery] string path) => { ctrl.HttpContext = ctx; return ctrl.List(path); });
            group_FilesController.MapGet("Content", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromQuery] string path) => { ctrl.HttpContext = ctx; return await ctrl.ReadContent(path); });
            group_FilesController.MapPost("Content", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromBody] SaveTextRequest request) => { ctrl.HttpContext = ctx; return await ctrl.WriteContent(request); });
            group_FilesController.MapPost("Mkdir", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromBody] PathRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Mkdir(request); });
            group_FilesController.MapPost("Rename", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromBody] RenameRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Rename(request); });
            group_FilesController.MapDelete("", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromQuery] string path, [FromQuery] bool recursive = false) => { ctrl.HttpContext = ctx; return await ctrl.Delete(path, recursive); });
            group_FilesController.MapPost("Upload", async ([FromServices] FilesController ctrl, HttpContext ctx, [FromQuery] string path, IFormFile? file) => { ctrl.HttpContext = ctx; return await ctrl.Upload(path, file); }).DisableAntiforgery();

            var group_GroupsController = app.MapGroup("/api/Groups");
            group_GroupsController.RequireAuthorization();
            group_GroupsController.MapGet("", async ([FromServices] GroupsController ctrl, HttpContext ctx, [FromQuery] GroupBizType bizType = GroupBizType.Command) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(bizType); });
            group_GroupsController.MapPost("", async ([FromServices] GroupsController ctrl, HttpContext ctx, [FromBody] SaveGroupRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_GroupsController.MapPut("{id:guid}", async ([FromServices] GroupsController ctrl, HttpContext ctx, Guid id, [FromBody] SaveGroupRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_GroupsController.MapDelete("{id:guid}", async ([FromServices] GroupsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });

            var group_HistoryController = app.MapGroup("/api/History");
            group_HistoryController.RequireAuthorization();
            group_HistoryController.MapGet("", async ([FromServices] HistoryController ctrl, HttpContext ctx, [AsParameters] ExecuteHistoryQuery query) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(query); });
            group_HistoryController.MapDelete("", async ([FromServices] HistoryController ctrl, HttpContext ctx, [FromQuery] int? olderThanDays) => { ctrl.HttpContext = ctx; return await ctrl.Clear(olderThanDays); });

            var group_LogsController = app.MapGroup("/api/Logs");
            group_LogsController.RequireAuthorization();
            group_LogsController.MapGet("Operations", async ([FromServices] LogsController ctrl, HttpContext ctx, [AsParameters] OperationLogQuery query) => { ctrl.HttpContext = ctx; return await ctrl.Operations(query); });
            group_LogsController.MapGet("Files", ([FromServices] LogsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.Files(); });
            group_LogsController.MapGet("Files/{name}", ([FromServices] LogsController ctrl, HttpContext ctx, string name, [FromQuery] int tail = 300) => { ctrl.HttpContext = ctx; return ctrl.FileContent(name, tail); });

            var group_OverviewController = app.MapGroup("/api/Overview");
            group_OverviewController.RequireAuthorization();
            group_OverviewController.MapGet("", async ([FromServices] OverviewController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.Get(); });

            var group_SchedulesController = app.MapGroup("/api/Schedules");
            group_SchedulesController.RequireAuthorization();
            group_SchedulesController.MapGet("", async ([FromServices] SchedulesController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(); });
            group_SchedulesController.MapPost("", async ([FromServices] SchedulesController ctrl, HttpContext ctx, [FromBody] SaveScheduleRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_SchedulesController.MapPut("{id:guid}", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id, [FromBody] SaveScheduleRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_SchedulesController.MapDelete("{id:guid}", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            group_SchedulesController.MapPost("{id:guid}/Toggle", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Toggle(id); });
            group_SchedulesController.MapPost("{id:guid}/RunNow", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.RunNow(id); });
            group_SchedulesController.MapGet("{id:guid}/Records", async ([FromServices] SchedulesController ctrl, HttpContext ctx, Guid id, [FromQuery] int page = 1, [FromQuery] int pageSize = 20) => { ctrl.HttpContext = ctx; return await ctrl.Records(id, page, pageSize); });

            var group_SmbMountsController = app.MapGroup("/api/SmbMounts");
            group_SmbMountsController.RequireAuthorization();
            group_SmbMountsController.MapGet("Support", ([FromServices] SmbMountsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.Support(); });
            group_SmbMountsController.MapGet("", async ([FromServices] SmbMountsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(); });
            group_SmbMountsController.MapPost("", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, [FromBody] SaveSmbMountRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_SmbMountsController.MapPut("{id:guid}", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, Guid id, [FromBody] SaveSmbMountRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_SmbMountsController.MapDelete("{id:guid}", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            group_SmbMountsController.MapPost("{id:guid}/Mount", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Mount(id); });
            group_SmbMountsController.MapPost("{id:guid}/Unmount", async ([FromServices] SmbMountsController ctrl, HttpContext ctx, Guid id) =>
            {
                ctrl.HttpContext = ctx;
                SmbMountsController.UnmountRequest? request = null;
                if (ctx.Request.HasJsonContentType() && ctx.Request.ContentLength is not (null or 0))
                {
                    request = await ctx.Request.ReadFromJsonAsync<SmbMountsController.UnmountRequest>(LinuxWebTool.WebHost.Composition.AppJsonSerializerContext.Default.UnmountRequest);
                }
                return await ctrl.Unmount(id, request);
            });

            var group_WebDavMountsController = app.MapGroup("/api/WebDavMounts");
            group_WebDavMountsController.RequireAuthorization();
            group_WebDavMountsController.MapGet("Support", ([FromServices] WebDavMountsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.Support(); });
            group_WebDavMountsController.MapGet("", async ([FromServices] WebDavMountsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(); });
            group_WebDavMountsController.MapPost("", async ([FromServices] WebDavMountsController ctrl, HttpContext ctx, [FromBody] SaveWebDavMountRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_WebDavMountsController.MapPut("{id:guid}", async ([FromServices] WebDavMountsController ctrl, HttpContext ctx, Guid id, [FromBody] SaveWebDavMountRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_WebDavMountsController.MapDelete("{id:guid}", async ([FromServices] WebDavMountsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            group_WebDavMountsController.MapPost("{id:guid}/Mount", async ([FromServices] WebDavMountsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Mount(id); });
            group_WebDavMountsController.MapPost("{id:guid}/Unmount", async ([FromServices] WebDavMountsController ctrl, HttpContext ctx, Guid id) =>
            {
                ctrl.HttpContext = ctx;
                WebDavMountsController.WebDavUnmountRequest? request = null;
                if (ctx.Request.HasJsonContentType() && ctx.Request.ContentLength is not (null or 0))
                {
                    request = await ctx.Request.ReadFromJsonAsync<WebDavMountsController.WebDavUnmountRequest>(LinuxWebTool.WebHost.Composition.AppJsonSerializerContext.Default.WebDavUnmountRequest);
                }
                return await ctrl.Unmount(id, request);
            });

            var group_MountTasksController = app.MapGroup("/api/MountTasks").RequireAuthorization();
            group_MountTasksController.MapGet("{id:guid}", ([FromServices] MountTasksController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return ctrl.Get(id); });

            var group_RcloneMountsController = app.MapGroup("/api/RcloneMounts");
            group_RcloneMountsController.RequireAuthorization();
            group_RcloneMountsController.MapGet("Support", ([FromServices] RcloneMountsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.Support(); });
            group_RcloneMountsController.MapGet("", async ([FromServices] RcloneMountsController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(); });
            group_RcloneMountsController.MapPost("", async ([FromServices] RcloneMountsController ctrl, HttpContext ctx, [FromBody] SaveRcloneMountRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_RcloneMountsController.MapPut("{id:guid}", async ([FromServices] RcloneMountsController ctrl, HttpContext ctx, Guid id, [FromBody] SaveRcloneMountRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_RcloneMountsController.MapDelete("{id:guid}", async ([FromServices] RcloneMountsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            group_RcloneMountsController.MapPost("{id:guid}/Mount", async ([FromServices] RcloneMountsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Mount(id); });
            group_RcloneMountsController.MapPost("{id:guid}/Unmount", async ([FromServices] RcloneMountsController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Unmount(id); });

            var group_SystemStatusController = app.MapGroup("/api/SystemStatus");
            group_SystemStatusController.RequireAuthorization();
            group_SystemStatusController.MapGet("", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, CancellationToken cancellationToken) => { ctrl.HttpContext = ctx; return await ctrl.Get(cancellationToken); });
            group_SystemStatusController.MapGet("History", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.History(hours); });
            group_SystemStatusController.MapGet("DiskHistory", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.DiskHistory(hours); });
            group_SystemStatusController.MapGet("NetHistory", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.NetHistory(hours); });
            group_SystemStatusController.MapGet("ProcessHistory", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.ProcessHistory(hours); });
            group_SystemStatusController.MapGet("ResourceHistory", async ([FromServices] SystemStatusController ctrl, HttpContext ctx, [FromQuery] int hours = 6) => { ctrl.HttpContext = ctx; return await ctrl.ResourceHistory(hours); });

            var group_TranscodeController = app.MapGroup("/api/Transcode");
            group_TranscodeController.RequireAuthorization();
            group_TranscodeController.MapGet("Jobs", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromQuery] int page = 1, [FromQuery] int pageSize = 20, [FromQuery] TranscodeJobStatus? status = null, [FromQuery] Guid? watchRuleId = null) => { ctrl.HttpContext = ctx; return await ctrl.Jobs(page, pageSize, status, watchRuleId); });
            group_TranscodeController.MapPost("Submit", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromBody] TranscodeSubmitRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Submit(request); });
            group_TranscodeController.MapPost("Jobs/{id:guid}/Cancel", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Cancel(id); });
            group_TranscodeController.MapPost("Jobs/Retry/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.Retry(id); });
            group_TranscodeController.MapPost("Jobs/ClearFinished", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.ClearFinished(); });
            group_TranscodeController.MapGet("Presets", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.Presets(); });
            group_TranscodeController.MapPost("Presets", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromBody] SavePresetRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreatePreset(request); });
            group_TranscodeController.MapPut("Presets/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id, [FromBody] SavePresetRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdatePreset(id, request); });
            group_TranscodeController.MapDelete("Presets/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.DeletePreset(id); });
            group_TranscodeController.MapGet("Presets/Export", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.ExportPresets(); });
            group_TranscodeController.MapPost("Presets/Import", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromBody] List<PresetImportItem> items) => { ctrl.HttpContext = ctx; return await ctrl.ImportPresets(items); });
            group_TranscodeController.MapGet("WatchRules", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.WatchRules(); });
            group_TranscodeController.MapPost("WatchRules", async ([FromServices] TranscodeController ctrl, HttpContext ctx, [FromBody] SaveWatchRuleRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreateWatchRule(request); });
            group_TranscodeController.MapPut("WatchRules/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id, [FromBody] SaveWatchRuleRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdateWatchRule(id, request); });
            group_TranscodeController.MapDelete("WatchRules/{id:guid}", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.DeleteWatchRule(id); });
            group_TranscodeController.MapPost("WatchRules/{id:guid}/Toggle", async ([FromServices] TranscodeController ctrl, HttpContext ctx, Guid id) => { ctrl.HttpContext = ctx; return await ctrl.ToggleWatchRule(id); });
            group_TranscodeController.MapGet("DetectFfmpeg", async ([FromServices] TranscodeController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.DetectFfmpeg(); });

            var group_TerminalController = app.MapGroup("/api/Terminal");
            group_TerminalController.RequireAuthorization();
            group_TerminalController.MapGet("Support", ([FromServices] TerminalController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.Support(); });
            group_TerminalController.MapGet("Sessions", ([FromServices] TerminalController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.ListSessions(); });
            group_TerminalController.MapGet("Sessions/{sessionId}", ([FromServices] TerminalController ctrl, HttpContext ctx, string sessionId) => { ctrl.HttpContext = ctx; return ctrl.SessionDetails(sessionId); });
            group_TerminalController.MapPatch("Sessions/{sessionId}", ([FromServices] TerminalController ctrl, HttpContext ctx, string sessionId, [FromBody] LinuxWebTool.Contracts.Terminal.TerminalSessionUpdateRequest request) => { ctrl.HttpContext = ctx; return ctrl.UpdateSession(sessionId, request); });
            group_TerminalController.MapPost("Sessions/{sessionId}/Attachment", ([FromServices] TerminalController ctrl, HttpContext ctx, string sessionId) => { ctrl.HttpContext = ctx; return ctrl.AttachmentTicket(sessionId); });
            group_TerminalController.MapPost("Sessions", async ([FromServices] TerminalController ctrl, HttpContext ctx, [FromBody] LinuxWebTool.Contracts.Terminal.TerminalSessionCreateRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreateSession(request); });
            group_TerminalController.MapDelete("Sessions/{sessionId}", async ([FromServices] TerminalController ctrl, HttpContext ctx, string sessionId) => { ctrl.HttpContext = ctx; return await ctrl.CloseSession(sessionId); });

            var group_ApiKeysController = app.MapGroup("/api/ApiKeys");
            group_ApiKeysController.RequireAuthorization();
            group_ApiKeysController.MapGet("", async ([FromServices] ApiKeysController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetAll(); });
            group_ApiKeysController.MapPost("", async ([FromServices] ApiKeysController ctrl, HttpContext ctx, [FromBody] CreateApiKeyRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Create(request); });
            group_ApiKeysController.MapPut("{id}", async ([FromServices] ApiKeysController ctrl, HttpContext ctx, string id, [FromBody] UpdateApiKeyRequest request) => { ctrl.HttpContext = ctx; return await ctrl.Update(id, request); });
            group_ApiKeysController.MapDelete("{id}", async ([FromServices] ApiKeysController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.Delete(id); });
            group_ApiKeysController.MapPost("{id}/Toggle", async ([FromServices] ApiKeysController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.Toggle(id); });

            var group_FrpTunnelController = app.MapGroup("/api/FrpTunnel");
            group_FrpTunnelController.RequireAuthorization();
            group_FrpTunnelController.MapGet("Lines", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetLines(); });
            group_FrpTunnelController.MapGet("Lines/{id}", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.GetLine(id); });
            group_FrpTunnelController.MapPost("Lines", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx, [FromBody] CreateFrpTunnelLineRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreateLine(request); });
            group_FrpTunnelController.MapPut("Lines/{id}", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx, string id, [FromBody] UpdateFrpTunnelLineRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdateLine(id, request); });
            group_FrpTunnelController.MapDelete("Lines/{id}", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.DeleteLine(id); });
            group_FrpTunnelController.MapPost("Lines/{id}/Start", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.StartLine(id); });
            group_FrpTunnelController.MapPost("Lines/{id}/Stop", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.StopLine(id); });
            group_FrpTunnelController.MapGet("Lines/{id}/Logs", ([FromServices] FrpTunnelController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return ctrl.GetLineLogs(id); });
            group_FrpTunnelController.MapGet("Config", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetConfig(); });
            group_FrpTunnelController.MapPut("Config", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx, [FromBody] UpdateFrpConfigRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdateConfig(request); });
            group_FrpTunnelController.MapGet("Status", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetStatus(); });
            group_FrpTunnelController.MapPost("Start", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.Start(); });
            group_FrpTunnelController.MapPost("Stop", async ([FromServices] FrpTunnelController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.Stop(); });
            group_FrpTunnelController.MapGet("Logs", ([FromServices] FrpTunnelController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return ctrl.GetLogs(); });

            var group_GatewayController = app.MapGroup("/api/Gateway");
            group_GatewayController.RequireAuthorization();
            group_GatewayController.MapGet("Routes", async ([FromServices] GatewayController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetRoutes(); });
            group_GatewayController.MapPost("Routes", async ([FromServices] GatewayController ctrl, HttpContext ctx, [FromBody] SaveGatewayRouteRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreateRoute(request); });
            group_GatewayController.MapPut("Routes/{id}", async ([FromServices] GatewayController ctrl, HttpContext ctx, string id, [FromBody] SaveGatewayRouteRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdateRoute(id, request); });
            group_GatewayController.MapDelete("Routes/{id}", async ([FromServices] GatewayController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.DeleteRoute(id); });
            group_GatewayController.MapGet("Clusters", async ([FromServices] GatewayController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetClusters(); });
            group_GatewayController.MapPost("Clusters", async ([FromServices] GatewayController ctrl, HttpContext ctx, [FromBody] SaveGatewayClusterRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreateCluster(request); });
            group_GatewayController.MapPut("Clusters/{id}", async ([FromServices] GatewayController ctrl, HttpContext ctx, string id, [FromBody] SaveGatewayClusterRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdateCluster(id, request); });
            group_GatewayController.MapDelete("Clusters/{id}", async ([FromServices] GatewayController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.DeleteCluster(id); });
            group_GatewayController.MapGet("Websites", async ([FromServices] GatewayController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetWebsites(); });
            group_GatewayController.MapPost("Websites", async ([FromServices] GatewayController ctrl, HttpContext ctx, [FromBody] SaveGatewayWebsiteRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreateWebsite(request); });
            group_GatewayController.MapPut("Websites/{id}", async ([FromServices] GatewayController ctrl, HttpContext ctx, string id, [FromBody] SaveGatewayWebsiteRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdateWebsite(id, request); });
            group_GatewayController.MapDelete("Websites/{id}", async ([FromServices] GatewayController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.DeleteWebsite(id); });
            group_GatewayController.MapGet("TcpRoutes", async ([FromServices] GatewayController ctrl, HttpContext ctx) => { ctrl.HttpContext = ctx; return await ctrl.GetTcpRoutes(); });
            group_GatewayController.MapPost("TcpRoutes", async ([FromServices] GatewayController ctrl, HttpContext ctx, [FromBody] SaveGatewayTcpRouteRequest request) => { ctrl.HttpContext = ctx; return await ctrl.CreateTcpRoute(request); });
            group_GatewayController.MapPut("TcpRoutes/{id}", async ([FromServices] GatewayController ctrl, HttpContext ctx, string id, [FromBody] SaveGatewayTcpRouteRequest request) => { ctrl.HttpContext = ctx; return await ctrl.UpdateTcpRoute(id, request); });
            group_GatewayController.MapDelete("TcpRoutes/{id}", async ([FromServices] GatewayController ctrl, HttpContext ctx, string id) => { ctrl.HttpContext = ctx; return await ctrl.DeleteTcpRoute(id); });
        }
    }
}
