using System.Text;
using System.Text.Json;
namespace LinuxWebTool.Infrastructure.Features.EasyTier.Adapters;

/// <summary>
/// EasyTier 节点 TOML 配置生成与校验器
/// </summary>
public static class EasyTierConfigGenerator
{
    public static string GenerateToml(EasyTierNodeEntity entity)
    {
        if (!string.IsNullOrWhiteSpace(entity.RawTomlOverride))
        {
            return entity.RawTomlOverride.Trim();
        }

        var sb = new StringBuilder();
        sb.AppendLine($"# Generated by LinuxWebTool EasyTier Manager at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"inst_name = \"{EscapeTomlString(entity.InstanceName)}\"");
        sb.AppendLine($"network_name = \"{EscapeTomlString(entity.NetworkName)}\"");

        if (!string.IsNullOrWhiteSpace(entity.NetworkSecret))
        {
            sb.AppendLine($"network_secret = \"{EscapeTomlString(entity.NetworkSecret)}\"");
        }

        if (!string.IsNullOrWhiteSpace(entity.VirtualIpv4))
        {
            sb.AppendLine($"ipv4 = \"{EscapeTomlString(entity.VirtualIpv4)}\"");
        }

        sb.AppendLine($"dhcp = {(entity.EnableDhcp ? "true" : "false")}");

        // 兼容 CoreBinary [network_identity] 表与 FFI 顶层字段
        sb.AppendLine("[network_identity]");
        sb.AppendLine($"network_name = \"{EscapeTomlString(entity.NetworkName)}\"");
        sb.AppendLine($"network_secret = \"{EscapeTomlString(entity.NetworkSecret ?? "")}\"");
        sb.AppendLine();

        // Listeners
        var listeners = DeserializeList(entity.ListenersJson);
        if (listeners.Count > 0)
        {
            var normalized = NormalizeListeners(listeners);
            sb.AppendLine($"listeners = [{string.Join(", ", normalized.Select(l => $"\"{EscapeTomlString(l)}\""))}]");
        }
        else
        {
            sb.AppendLine("no_listener = true");
        }

        // Peers (同时支持 [[peer]] 表数组与 peers 列表)
        var peers = DeserializeList(entity.PeersJson);
        if (peers.Count > 0)
        {
            sb.AppendLine($"peers = [{string.Join(", ", peers.Select(p => $"\"{EscapeTomlString(p)}\""))}]");
            foreach (var p in peers)
            {
                sb.AppendLine();
                sb.AppendLine("[[peer]]");
                sb.AppendLine($"uri = \"{EscapeTomlString(p)}\"");
            }
        }

        // Proxy networks
        var proxyNetworks = DeserializeList(entity.ProxyNetworksJson);
        if (proxyNetworks.Count > 0)
        {
            sb.AppendLine($"proxy_networks = [{string.Join(", ", proxyNetworks.Select(pn => $"\"{EscapeTomlString(pn)}\""))}]");
            foreach (var pn in proxyNetworks)
            {
                sb.AppendLine();
                sb.AppendLine("[[proxy_network]]");
                sb.AppendLine($"cidr = \"{EscapeTomlString(pn)}\"");
            }
        }

        // Routes
        var routes = DeserializeList(entity.RoutesJson);
        if (routes.Count > 0)
        {
            sb.AppendLine($"routes = [{string.Join(", ", routes.Select(r => $"\"{EscapeTomlString(r)}\""))}]");
        }

        return sb.ToString();
    }

    public static string GenerateToml(CreateEasyTierNodeRequest request)
    {
        if (!string.IsNullOrWhiteSpace(request.RawTomlOverride))
        {
            return request.RawTomlOverride.Trim();
        }

        var sb = new StringBuilder();
        sb.AppendLine($"inst_name = \"{EscapeTomlString(request.InstanceName)}\"");
        sb.AppendLine($"network_name = \"{EscapeTomlString(request.NetworkName)}\"");

        if (!string.IsNullOrWhiteSpace(request.NetworkSecret))
        {
            sb.AppendLine($"network_secret = \"{EscapeTomlString(request.NetworkSecret)}\"");
        }

        if (!string.IsNullOrWhiteSpace(request.VirtualIpv4))
        {
            sb.AppendLine($"ipv4 = \"{EscapeTomlString(request.VirtualIpv4)}\"");
        }

        sb.AppendLine($"dhcp = {(request.EnableDhcp ? "true" : "false")}");

        // 兼容 CoreBinary [network_identity] 表与 FFI 顶层字段
        sb.AppendLine("[network_identity]");
        sb.AppendLine($"network_name = \"{EscapeTomlString(request.NetworkName)}\"");
        sb.AppendLine($"network_secret = \"{EscapeTomlString(request.NetworkSecret ?? "")}\"");
        sb.AppendLine();

        var listeners = request.Listeners ?? [];
        if (listeners.Count > 0)
        {
            var normalized = NormalizeListeners(listeners);
            sb.AppendLine($"listeners = [{string.Join(", ", normalized.Select(l => $"\"{EscapeTomlString(l)}\""))}]");
        }
        else
        {
            sb.AppendLine("no_listener = true");
        }

        // Peers (同时支持 [[peer]] 表数组与 peers 列表)
        var peers = request.Peers ?? [];
        if (peers.Count > 0)
        {
            sb.AppendLine($"peers = [{string.Join(", ", peers.Select(p => $"\"{EscapeTomlString(p)}\""))}]");
            foreach (var p in peers)
            {
                sb.AppendLine();
                sb.AppendLine("[[peer]]");
                sb.AppendLine($"uri = \"{EscapeTomlString(p)}\"");
            }
        }

        // Proxy networks
        var proxyNetworks = request.ProxyNetworks ?? [];
        if (proxyNetworks.Count > 0)
        {
            sb.AppendLine($"proxy_networks = [{string.Join(", ", proxyNetworks.Select(pn => $"\"{EscapeTomlString(pn)}\""))}]");
            foreach (var pn in proxyNetworks)
            {
                sb.AppendLine();
                sb.AppendLine("[[proxy_network]]");
                sb.AppendLine($"cidr = \"{EscapeTomlString(pn)}\"");
            }
        }

        var routes = request.Routes ?? [];
        if (routes.Count > 0)
        {
            sb.AppendLine($"routes = [{string.Join(", ", routes.Select(r => $"\"{EscapeTomlString(r)}\""))}]");
        }

        return sb.ToString();
    }

    public static bool ValidateConfig(string toml, out string? error)
    {
        if (string.IsNullOrWhiteSpace(toml))
        {
            error = "配置内容不能为空";
            return false;
        }

        if (EasyTierNativeMethods.ProbeLibrary(out _))
        {
            try
            {
                var ret = EasyTierNativeMethods.parse_config(toml);
                if (ret != 0)
                {
                    error = EasyTierNativeMethods.GetLastErrorMessage();
                    return false;
                }
                error = null;
                return true;
            }
            catch (Exception ex)
            {
                error = $"调用 parse_config 发生异常: {ex.Message}";
                return false;
            }
        }

        // 基础语法结构启发式校验
        if (!toml.Contains("inst_name"))
        {
            error = "缺少必需的 inst_name 字段";
            return false;
        }

        error = null;
        return true;
    }

    private static List<string> DeserializeList(string? json)
    {
        if (string.IsNullOrWhiteSpace(json)) return [];
        try
        {
            return JsonSerializer.Deserialize(json, EasyTierJsonContext.Default.ListString) ?? [];
        }
        catch
        {
            return [];
        }
    }

    private static List<string> NormalizeListeners(List<string> listeners)
    {
        var result = new List<string>();
        foreach (var item in listeners)
        {
            var trimmed = item.Trim();
            if (string.IsNullOrEmpty(trimmed)) continue;

            // 纯端口号（例如 "11010"）自动补充 tcp、udp、wg 的 IPv4 与 IPv6 全套监听
            if (int.TryParse(trimmed, out var port) && port > 0 && port <= 65535)
            {
                result.Add($"tcp://0.0.0.0:{port}");
                result.Add($"udp://0.0.0.0:{port}");
                result.Add($"wg://0.0.0.0:{port + 1}");
                result.Add($"tcp://[::]:{port}");
                result.Add($"udp://[::]:{port}");
                result.Add($"wg://[::]:{port + 1}");
            }
            // 缺少 scheme 的 host:port（例如 "0.0.0.0:11010" 或 ":11010"）
            else if (trimmed.Contains(':') && !trimmed.Contains("://"))
            {
                var hostPort = trimmed.TrimStart(':');
                if (!hostPort.Contains(':')) hostPort = $"0.0.0.0:{hostPort}";
                result.Add($"tcp://{hostPort}");
                result.Add($"udp://{hostPort}");
            }
            // wg:// 前缀处理（默认端口 11011）
            else if (trimmed.StartsWith("wg://", StringComparison.OrdinalIgnoreCase))
            {
                var rest = trimmed[5..];
                if (string.Equals(rest, "0.0.0.0", StringComparison.OrdinalIgnoreCase)) result.Add("wg://0.0.0.0:11011");
                else if (string.Equals(rest, "[::]", StringComparison.OrdinalIgnoreCase) || string.Equals(rest, "::", StringComparison.OrdinalIgnoreCase)) result.Add("wg://[::]:11011");
                else if (int.TryParse(rest.TrimStart(':'), out var p)) result.Add($"wg://0.0.0.0:{p}");
                else if (!rest.Contains(':')) result.Add($"{trimmed}:11011");
                else result.Add(trimmed);
            }
            // udp:// 前缀处理（默认端口 11010）
            else if (trimmed.StartsWith("udp://", StringComparison.OrdinalIgnoreCase))
            {
                var rest = trimmed[6..];
                if (string.Equals(rest, "0.0.0.0", StringComparison.OrdinalIgnoreCase)) result.Add("udp://0.0.0.0:11010");
                else if (string.Equals(rest, "[::]", StringComparison.OrdinalIgnoreCase) || string.Equals(rest, "::", StringComparison.OrdinalIgnoreCase)) result.Add("udp://[::]:11010");
                else if (int.TryParse(rest.TrimStart(':'), out var p)) result.Add($"udp://0.0.0.0:{p}");
                else if (!rest.Contains(':')) result.Add($"{trimmed}:11010");
                else result.Add(trimmed);
            }
            // tcp:// 前缀处理（默认端口 11010）
            else if (trimmed.StartsWith("tcp://", StringComparison.OrdinalIgnoreCase))
            {
                var rest = trimmed[6..];
                if (string.Equals(rest, "0.0.0.0", StringComparison.OrdinalIgnoreCase)) result.Add("tcp://0.0.0.0:11010");
                else if (string.Equals(rest, "[::]", StringComparison.OrdinalIgnoreCase) || string.Equals(rest, "::", StringComparison.OrdinalIgnoreCase)) result.Add("tcp://[::]:11010");
                else if (int.TryParse(rest.TrimStart(':'), out var p)) result.Add($"tcp://0.0.0.0:{p}");
                else if (!rest.Contains(':')) result.Add($"{trimmed}:11010");
                else result.Add(trimmed);
            }
            else
            {
                result.Add(trimmed);
            }
        }
        return result;
    }

    private static string EscapeTomlString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
